### ISSUE TITLE
base64 encoding

### ISSUE THREAD

**Issue by mdomke** [jcderr/concourse-kubernetes-resource#2]
I was about to create the same resource in more or less the same way that you did . Nevertheless I was wondering why you require the certificates and keys to be base64 encoded, since the `PEM` files are base64 encoded anyhow. In the way you implemented it I would have to pass the keys and certificates through the `base64` utility before adding them to my pipeline specification instead of just copy-pasting them. Is there any particular reason for it?

**Comment by jcderr** [comment]
That's a perfectly good point. I'm probably stuck in an anti-pattern of trying to keep things all on one line to tidy up my resources.

**Comment by jcderr** [comment]
I have a rework in process for a few things anyhow - and will probably reimplement this in Go. I'll keep this in mind as I wrap that up.
