### ISSUE TITLE
why indirect through files?

### ISSUE THREAD

**Issue by andrewrk** [jcderr/concourse-kubernetes-resource#9]
what's the purpose of this?

```
# get image name
IMG_FILE=$(jq -r .params.image_name < "$payload")
IMG=$(cat "$IMG_FILE")
TAG_FILE=$(jq -r .params.image_tag < "$payload")
TAG=$(cat "$TAG_FILE")
IMG="$IMG:$TAG"
```

why can't the image name and tag be in the params directly?

**Comment by andrewrk** [comment]
answer is that you want the value to be dynamic, and if it was a param directly, you'd have to hardcode the tag and image name in the pipeline config.

**Comment by rickr** [comment]
Where exactly are you supposed to place this file? Couldn't you use templating and env vars?
